### ISSUE TITLE
there is a BibTex in literature / references.bib, which is not up to date: PostgreSQL

### ISSUE THREAD

**Issue by ausdree** [htw-pv3/literature#105]
- [x] update the PostgreSQL BibTex

- [x] make pull request

**Comment by EvgeniaSyk** [comment]
Hi, ich denke ich mache das schon in Issue #90.

**Comment by ausdree** [comment]
Hi Evgenia, 

kannst du bitte die neue Version von einem anderen Programm einfügen? Dann haben wir beide einen Beitrag :)

**Comment by Ludee** [comment]
Improve commit message: `Update version number #105`
