### ISSUE TITLE
Add minutes

### ISSUE THREAD

**Issue by Ludee** [htw-pv3/literature#11]
- [x] 1.
- [x] 2.
- [x] 3.
- [x] 4. Burak

**Comment by khelfen** [comment]
Wups grad gesehen, dass prot-3 jetzt 2x da ist. Meine Version ist vollständig in md umgeschrieben

**Comment by khelfen** [comment]
Merged prot-3 into master

**Comment by khelfen** [comment]
What is the best way to move the data into the protokolle folder?
