### ISSUE TITLE
Add crib sheet for git

### ISSUE THREAD

**Issue by Ludee** [htw-pv3/literature#13]
start and document git commands

**Comment by Ludee** [comment]
Denke das Sheet ist jetzt schon etwas überladen!
Lieber die wichtigsten Befehle mit guter Dokumentation und passendem Workflow als alles.
Eine Sammlung von bestehenden Dokumenten ist ebenfalls hilfreich!

**Comment by Ludee** [comment]
![git-cheat-sheet-large01](https://user-images.githubusercontent.com/14353512/80648952-5fb73080-8a71-11ea-8c5a-1297b1c4a9fd.png)

**Comment by Ludee** [comment]
Improve the existing git-cheat-cheat.
Adding a .png to git is not optimal, please document why @TheBlackBlade 
Divide into 2 separate (text) files: 

- [ ] CONTRIBUTE.md (GitHub workflow, see [this example](https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md)
- [ ] crib-sheet_git.md (git setup, merging, ssh)

Focus is on necessary commands, collect links to existing sources.

Another thing, (source: Huelk) is wrong in so many ways. Please start an issue to discuss and integrate proper citation!

**Comment by TheBlackBlade** [comment]
> Adding a .png to git is not optimal, please document why @TheBlackBlade
It's sub-optimal, because a changed pixel in the image file translates to a completely new file for git. I thought his would be neglectable, since the file will not be changed.
What is your professional solution to reference problems, external cloud storage or link libary?

**Comment by nailend** [comment]
Probably a markdown file with a proper structured collection of links to existing cheat-sheets might be one solution?

e.g.

## git

[git-cheat-sheet by github](https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdf)

[git-cheat-sheet by tower](https://user-images.githubusercontent.com/14353512/80648952-5fb73080-8a71-11ea-8c5a-1297b1c4a9fd.png)

## SQL

[PostgreSQL-cheat-sheet](https://sp.postgresqltutorial.com/wp-content/uploads/2018/03/PostgreSQL-Cheat-Sheet.pdf)

## Python/conda
[conda-cheat-sheet](https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf)

### pandas

[pandas-cheat-sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

### matplotlib

[matplotlib-cheat-sheet](https://python-graph-gallery.com/wp-content/uploads/Matplotlib_cheatsheet_datacamp.png)

### seaborn

[seaborn-cheat-sheat](https://python-graph-gallery.com/wp-content/uploads/Seaborn_Cheatsheet_Datacamp.png)

**Comment by TheBlackBlade** [comment]
@Ludee When I asked the group about this problem, @khelfen mention the "large file storage" extention for git (https://git-lfs.github.com/).
with that, large picture files or videos can be remotely saved and the git only contains a text pointer to the storage location.
Please review and evaluate, if this would be an appropriate method of handling images and videos in the future.

**Comment by khelfen** [comment]
So let's just go on as @nailend suggested? So that we can close all pending issues in this repo

**Comment by Ludee** [comment]
> Please review and evaluate, if this would be an appropriate method of handling images and videos in the future.

This looks interesting. I'm not a big fan of too much git extensions. Handling images in Issues an PR is already good. And git isn't made for media and data.
