### ISSUE TITLE
Problem with dev Branch, DO NOT CLONE/PULL/MERGE DEV BEFORE BUG IS FIXED!!!

### ISSUE THREAD

**Issue by JohannesBru** [htw-pv3/literature#144]
There is currently a version issue with the development branch.

Somehow an old version of the dev branch was restored (around 160 commits) (Should have around 200 commits).

Please be carefull if you clone or pull the current Version of the dev branch you are cloning the version with 160 commits. (You should use the branch with ~200 commits)

I'm investigating the issue at the moment and try to fix it. (Therefore I restored branches of feature #131,  #133 and #138)

The current Pull request #143 is trying to merge the 40 commits difference.

I think somehow the current master Version with 158 commits got merged into the dev branch.

**Comment by JohannesBru** [comment]
I merged PR #143 with feature-141 into dev which restored up to date status.

**Comment by Borni16** [comment]
Thanks a lot for the effort! 

I was confused that it said I have 40 commits in 7 documents to merge in my pull request #143 , but I had no idea where these changes came from.

I also had a merge conflict in the crib-cheat_git.md when I tried to pull the dev yesterday. However I think I was able to solve this conflict.

**Comment by JohannesBru** [comment]
You're welcome! 

I pretty shure now that the current master got merged in the more up to date dev which caused the 40 commits. These also included commits from the last semesters. 

We should have merged the dev from last semester into the master first, before the SoSe2022 group started working on dev.

**Comment by JohannesBru** [comment]
As this issue is fixed im going to close it!
