### ISSUE TITLE
Can't push Protocol 3

### ISSUE THREAD

**Issue by khelfen** [htw-pv3/literature#16]
Ich hab remote einen neuen Branch erstellt für das Protokoll 3 und kann den leider nicht pushen:
* Permission to htw-pv3/literature.git denied to khelfen

![Screenshot - 29_04](https://user-images.githubusercontent.com/46815982/80635322-042e7800-8a5c-11ea-8b11-71fd6a8627dc.png)

Habe bereits
* https://stackoverflow.com/a/11368701 versucht und
* https://stackoverflow.com/a/49893780

Beides ohne Erolg.

@Ludee eine Idee woran das liegt?

**Comment by Ludee** [comment]
Habe beim Erstellen des neuen Repos die Rechte des Teams verkackt. Anstelle von Write habe ich nur Read für alle angeklickt. Danke fürs finden und sorry.
