### ISSUE TITLE
updating course description in README.md

### ISSUE THREAD

**Issue by Tim-Albert** [htw-pv3/literature#194]
## Checklist
- [x]  create an issue 

- [x]  solve the issue locally

- [x] push your commits

- [x] submit a pull request

- [x] close the issue

**Comment by s0573684** [comment]
Die Aufgabe wurde im issue sinnvoll unterteilt. Die Kurzbeschreibung des Kurses beinhaltet in meinen Augen alle wichtigen Punkte von Inhalten des Kurses bis Bewertung.
