### ISSUE TITLE
Adding Miniconda to references.bib

### ISSUE THREAD

**Issue by s0573684** [htw-pv3/literature#195]
- [x] create an issue
- [x] solve issue locally 
- [x] commit and push changings 
- [x] submit and pull request
- [x] close the issue

**Comment by Tim-Albert** [comment]
Du hast alle notwendigen Schritte erfüllt. 
Deine Checkliste und der Issue-Verlauf sehen Fehlerfrei aus. Die Idee des Hinzufügens der Miniconda finde ich großartig!
Du hast Issue erstellt-->Issue localy gelöst --> commited und gepushed --> pull requested --> Issue geschlossen.
