### ISSUE TITLE
delete duplicates

### ISSUE THREAD

**Issue by nailend** [htw-pv3/literature#29]
Delete the duplicate protocols in the main folder.
__Only__ do this  __after__ merging all feature/add-protocols... to the master to avoid merge conflicts.

**Comment by nailend** [comment]
#11

**Comment by khelfen** [comment]
merged PR #28 #11

**Comment by TheBlackBlade** [comment]
If you merged the branches, please check if the issue can be closed. Else write down open tasks.

**Comment by Braak-1991** [comment]
Removed the duplicate in #25 after moving it to the protokoll folder.

**Comment by nailend** [comment]
- file [2020-04-22-protocol-3.md](2020-04-22-protocol-3.md) still need to be removed.
- to avoid complicated merge-conflicts in our first git-week, I would suggest to postpone this task to the next week
