### ISSUE TITLE
Add relevant websites and references for pv simulations

### ISSUE THREAD

**Issue by FaidoEwald** [htw-pv3/literature#32]
I am about to rebuild the linklist for literature into two divisions, because there are two prinicipal contents inside:
1. links to git-literature
2. links PV (scaling and tech-inside)

Why? I would like to collect more usefull links to PV. And I don't want to scroll over git and/or other stuff to reach this content.

**So, please take part and share the websites and webtools you like!**

Sorry @PhuongThaoBui ! You misunderstood my aim. I'll try to describe it better next time!

**Comment by Ludee** [comment]
The contributed sources are really good. Thanks!
But the file naming doesn't follow good practice and you are mixing German and English. 
Please include the sources as proper "bibtex" in the shared .bib file. 
[Use the bib-type "@Misc" to enter webpages.](https://tex.stackexchange.com/questions/3587/how-can-i-use-bibtex-to-cite-a-web-page)

**Comment by FaidoEwald** [comment]
@Ludee thank you for your comment. I transformed the .md into a .bib file using the shared_literature.bib and the @misc as an example. The result can be seen in the new file I created called: "shared_literature_PV_FE.bib". 
I chose not to integrate it into shared_literature.bib in order to avoid conflicts.
**There will have to be a merge with the shared_literature.bib afterwards, how you proposed!**
What do you mean by "naming doesn't follow good practice"? You want me to call the file like this: "2020-05-06_shared_literature_PV_FE.bib"?

[ ] merge shared_literature_PV_FE.bib with shared_literature.bib
[ ] overwork "git_literature.md" to a bib-File with @misc
[ ] merge git_literature.bib with shared_literature.bib
