### ISSUE TITLE
 Literatur-Bibtex

### ISSUE THREAD

**Issue by Flo-tru** [htw-pv3/literature#33]
Bibtex zu den Themen Git, Github, PV-Modelellierung und Sonnja

**Comment by khelfen** [comment]
Please add the new literatur entries directly into the shared_literature.bib and don't create a new bib file

**Comment by Ludee** [comment]
The issue title is not specific enough.
The "literature" is divided into separate files. Please rename.

**Comment by khelfen** [comment]
@Flo-tru or anyone still working on this? We want to clean up our git and this either needs to be resolved or closed if we want to go on

**Comment by nailend** [comment]
I think the branch [iss33] is broke. I started a new one and integrated the new literature in shared_literature.bib.

p.s. Very nice docu, how to rewrite history https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
