### ISSUE TITLE
Add literature about data classification

### ISSUE THREAD

**Issue by meloeckert** [htw-pv3/literature#36]
I will add some Literature about the topic Data Classification.
First I will wait for  the two people that are already working on creating  the Literature- Bibtex file. 
Once the .bib-file from #32 is created  I will add my contribution.

**Comment by Ludee** [comment]
I would love to have the data classification document properly. That's a "significant contribution"! (Yes I like data management too much sometimes)

**Comment by meloeckert** [comment]
By the way @Ludee , I still need to be granted permission to the repository, so that I can later push my contribution

**Comment by meloeckert** [comment]
![image](https://user-images.githubusercontent.com/64534574/81313982-dadba080-9088-11ea-8ec8-dd620822e82b.png)

**Comment by meloeckert** [comment]
@Ludee, I want to push my branch as a test, but it still doesn't work. Am I doing something wrong here?

**Comment by Ludee** [comment]
You were not yet member of the group. I added you and now you have write access to the repos!

**Comment by khelfen** [comment]
@meloeckert are you still working on this?
