### ISSUE TITLE
Clean up our git!

### ISSUE THREAD

**Issue by TheBlackBlade** [htw-pv3/literature#39]
*"Unser git(Schiff) muss schöner werden."*
Demnach ist dieses Issue für commits gedacht, die das git sortieren. Dazu gehören:

- [ ] Neue Ordner erstellen
- [ ] Dateien in andere Ordner verschieben
- [ ] Datei umbenennen nach Namenskonvention (YYYY-MM-DD_TITLE_OPTIONALS)
- [ ] Duplikate entfernen @Patrickhs 

Das Issue kann offen bleiben, da ich denke, dass stetige Änderungen es notwendig machen werden, das git stehst aufzuräumen.

Ideen und Verbesserungsvorschläge sind gerne gesehen :D

- [ ] #5 
- [x] #32 (issue closed)
- [ ] #33
- [x] #47

**Comment by Ludee** [comment]
It makes sense to use this issue as "top level issue" and link more specific issues. 
It is possible for everybody to edit the first post. Make a list and reference the issue numbers.

**Comment by TheBlackBlade** [comment]
A general question: How would be start changing the folder structure of the git, while some branches are still active? Wouldn't this result in merging conflicts or other errors? What is the best practice for organisational changes?

**Comment by FaidoEwald** [comment]
Hi, I would like to merge "shared_literature_PV_FE.bib" into "shared_literature.bib".
Which branch should I use for this edit? Should I wait until another merge is done?

open: 
- [ ] merge: "shared_literature_PV_FE.bib" into "shared_literature.bib"
- [ ] switch the infromation in "git_literature.md" to "shared_literature.bib" using the macro @misc (see i.e. "shared_literature_PV_EFH.bib" in main folder

**Comment by mauricio-ocampo** [comment]
I think it would be better o change the name of the file called "shared_literature.bib" ´cause that´s a BibTex file and describe the Software Used in the Project and the hosting service i.e. GitHub, so I propose to change it to "software&OnlineTools.bib". Also there is already a Shared Literature BibTex File called "shared_literature_PV_FE.bib" which has an Online Tool called "PVSol_online" and that should be part of the software and online tools used in the project and not as literature I guess. What do you think?

**Comment by Ludee** [comment]
The goal is to have one single .bib file containing all "literature" (software, websites, papers...).
Usually this is called _references.bib_.

**Comment by FaidoEwald** [comment]
> The goal is to have one single .bib file containing all "literature" (software, websites, papers...).
> Usually this is called _references.bib_.

Sounds easy. I suggest to give the "references.bib" a certain structure like:

- Software
- OnlineTools
- literature solar engineering
- ...

@mauricio-ocampo

**Comment by mauricio-ocampo** [comment]
Yes I like that @FaidoEwald

**Comment by Ludee** [comment]
What a mess! Here is my plan for a quick clean up:

1. Merge all branches
2. Close all Issues
3. Merge duplicate files
