### ISSUE TITLE
Drop duplicate protocol

### ISSUE THREAD

**Issue by khelfen** [htw-pv3/literature#47]
At the moment we have two versions of the 2020-05-06 protocol

* This should be kept [2020-05-06_htw-pv3_postgresql_II.md](https://github.com/htw-pv3/literature/blob/master/protokolle/2020-05-06_htw-pv3_postgresql_II.md)
* This should be removed [2020-06-06_htw-pv3_postgresql_II.md](https://github.com/htw-pv3/literature/blob/master/protokolle/2020-06-06_htw-pv3_postgresql_II.md)

#39

**Comment by Patrickhs** [comment]
I will try to fix it.

**Comment by khelfen** [comment]
I suggest leaving it for now until all non-master branches are closed to avoid merge conflicts. But not 100% sure about this

**Comment by Patrickhs** [comment]
Ok, thanks. Then I'll leave it for now.

**Comment by nailend** [comment]
good to read about this
https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts
