### ISSUE TITLE
how to deal with merge-conflicts?

### ISSUE THREAD

**Issue by nailend** [htw-pv3/literature#52]
At one point or another we will have to deal with merge conflicts! Therefore I will offer to show how to deal with them after the next lecture around 17:30 to 18:00. This might take 15-20 minutes.

For this, 
- I will produce 2 new feature branches
- provoke a conflict between these branches
- request a PR
- solve the conflicts and merge them

**Comment by Ludee** [comment]
That would be awesome!

First goal is to avoid merge conflicts:

- Communication about developments
- Follow [Atomic Commits](https://www.freshconsulting.com/atomic-commits/)
- Close branches fast

Second goal is to solve existing commits:

- Don't panic! Everything can be fixed
- Using comparison/diff tools like [Meld](https://meldmerge.org/)
- Commit merges and communicate them
