### ISSUE TITLE
add a cheat sheet collection

### ISSUE THREAD

**Issue by nailend** [htw-pv3/literature#56]
The idea is to have a markdown file with a collection of links to existing cheat-sheet like mentioned in #13. 

please conrtibute to the file at branch: [feature/cheat-sheet-collection#56](https://github.com/htw-pv3/literature/blob/feature/cheat-sheet-collection%2356/cheat-sheet-collection.md)

**Comment by TheBlackBlade** [comment]
Looks very good! Can #13 be considered closed then @Ludee?
