### ISSUE TITLE
Merge literature into single file shared_literature

### ISSUE THREAD

**Issue by Ludee** [htw-pv3/literature#8]
Thanks for pushing your results!
Please merge [your bib file](https://github.com/htw-pv3/literature/blob/Helfenbein_Branch/literatur_Helfenbein_Kilian.bib) into the [shared_literature.bib](https://github.com/htw-pv3/literature/blob/Helfenbein_Branch/shared_literature.bib) and create a PR!

**Comment by khelfen** [comment]
Done

**Comment by Ludee** [comment]
Nope

**Comment by Ludee** [comment]
Genau! das Issue wird erst geschlossen, wenn der PR ein Revie hat, gemerged wurde und der Feature-Branch gelöscht wurde!
